backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # Stores images/videos
public_folder: "/uploads"

collections:
  # Homepage Sections
  - name: "home"
    label: "Homepage"
    files:
      - name: "hero"
        label: "Hero Section"
        file: "data/home.yml"
        fields:
          - { name: "title", label: "School Name", widget: "string" }
          - { name: "hero_image", label: "Hero Image", widget: "image" }
          - { name: "welcome_text", label: "Welcome Message", widget: "text" }

  # News Posts
  - name: "news"
    label: "News"
    folder: "data/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "content", label: "Content", widget: "markdown" }

  # Photo Gallery
  - name: "gallery"
    label: "Photo Gallery"
    folder: "data/gallery"
    create: true
    fields:
      - { name: "event_name", label: "Event Name", widget: "string" }
      - { name: "photos", label: "Photos", widget: "list", fields: [
          { name: "image", label: "Image", widget: "image" },
          { name: "caption", label: "Caption", widget: "string" }
        ]}

  # Videos
  - name: "videos"
    label: "Videos"
    files:
      - name: "featured_video"
        label: "Featured Video"
        file: "data/videos.yml"
        fields:
          - { name: "youtube_url", label: "YouTube URL", widget: "string" }